### ISSUE TITLE
在navication中的按钮点击弹出弹不出来

### ISSUE THREAD

**Issue by langyan1022** [MxABC/LBXAlertAction#1]
控制台报这个错误：
Warning: Attempt to present <UIAlertController: 0x12e6c9300> on <UINavigationController: 0x12e82ca00> whose view is not in the window hierarchy!

跟踪了下代码，应该是在getTopViewController 中出问题了，这个方法返回的result是window.rootViewController.

**Comment by MxABC** [comment]
有demo代码吗，发我看看呢，lbxia20091227@foxmail.com
